version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/php:8.2
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    user: vscode
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omna25_db
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
